package com.example.simplemvvm.utils

object Constants {
    const val BASE_URL = "https://lappen.in/lappen_app/api/"
    const val BASE_URL_ZIP_CODE = "https://staging-express.delhivery.com/c/api/pin-codes/json/"

    const val END_POINT = BASE_URL+"spacecrafts.json"

    const val END_POINT_HOME = "home"
    const val END_POINT_ZIP_CODE = ""
    const val END_POINT_PRODUCTS = "products"
    const val END_POINT_SEARCH_PRODUCT = "search-product?search="
    const val END_POINT_CATEGORY = "category"
    const val END_POINT_LOGIN = "login"
    const val END_POINT_CART = "cart"
    const val END_POINT_CANCEL_ORDER = "order-status"
    const val END_POINT_APPLY_RATING = "review"
    const val END_POINT_APPLY_COUPON = "apply-coupon-code"
    const val END_POINT_PLACE_ORDER = "order"
    const val END_POINT_FAQ = "faq-list"
    const val END_POINT_VERSION_UPDATE = "app-version"
    const val END_POINT_OUT_OF_STOCK_PRODUCT = "out-off-stock-product"
    const val END_POINT_ADD_ADDRESS = "shipping-address"
    const val END_POINT_RESEND_OTP = "resend-otp"
    const val END_POINT_VERIFY_OTP = "verify-otp"
    const val END_POINT_PLACE_ORDER_VIEW = "cart-view"
    const val END_POINT_WISH_LIST = "wish-list"
    const val END_POINT_FILTER = "display-product-filter"
    const val END_POINT_PROFILE = "profile"
    const val END_POINT_GET_WISH_LIST = "wish-list"
    const val END_POINT_CHECKOUT_CART = "check-out"
    const val END_POINT_GET_ADDRESS = "shipping-address"
    const val END_POINT_GET_NOTIFICATION = "user-notification-list"
    const val END_POINT_DELIVERY_OPTION = "delivery-option"
    const val END_POINT_DELETE_WISH_LIST = "wish-list"


    //Prefs
    const val PREF_TOKEN = "PREF_TOKEN"
    const val PREF_IS_LOGGED_IN = "PREF_IS_LOGGED_IN"
    const val PREF_PROFILE_PICTURE = "PREF_PROFILE_PICTURE"
    const val PREF_PROFILE_MOBILE_NUMBER = "PREF_PROFILE_MOBILE_NUMBER"
    const val PREF_PROFILE_FULL_NAME = "PREF_PROFILE_FULL_NAME"
    const val PREF_PROFILE_EMAIL = "PREF_PROFILE_EMAIL"
    const val PREF_PROFILE_GENDER = "PREF_PROFILE_GENDER"
    const val PREF_PROFILE_DATE_OF_BIRTH = "PREF_PROFILE_DATE_OF_BIRTH"
    const val PREF_USER_ID = "PREF_USER_ID"
    const val PREF_CART_COUNT = "PREF_CART_COUNT"
    const val PREF_SELECTED_PRODUCT_SIZE = "PREF_SELECTED_PRODUCT_SIZE"
    const val PREF_SELECTED_COLOR = "PREF_SELECTED_COLOR"

    //product id pref
    const val PREF_CATEGORY_ID = "PREF_CATEGORY_ID"
    const val PREF_SUB_CATEGORY_ID = "PREF_SUB_CATEGORY_ID"
    const val PREF_PRODUCT_CATEGORY_ID = "PREF_PRODUCT_CATEGORY_ID"
    const val PREFS_SEARCH_STRING = "PREFS_SEARCH_STRING"
    const val PREF_PRODUCT_TITLE = "PREF_PRODUCT_TITLE"
    const val PREF_PRODUCT_ID = "PREF_PRODUCT_ID"
    const val PREF_OFFER_AMOUNT = "PREF_OFFER_AMOUNT"
}